import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>aaaaa</h1>
        {data.recipes.map(item =>
          <div key={item.title}>
            <Image
                src={item.image}
                alt={item.title}
                width={160}
                height={90}
              />
            <p>{item.title}</p>
          </div>
        )}
      </main>
    </>
  )
}

export async function getServerSideProps({res}) {
  //s-maxage: secons this value is considered fresh
  //stale-while-revalidate: stale-while-revalidate.
  //The steal value will be rendered but in th background will be a petition for the new value

  res.setHeader(
    'Cache-Control',
    'public, s-maxage=3600, stale-while-revalidate=7200'
  )

  const response = await fetch(`https://api.spoonacular.com/recipes/random?number=10&apiKey=${process.env.SPOONACULAR_API_KEY}`)
  const data = await response.json()


  return { props: { data } }
}
