import Head from 'next/head'
import Image from 'next/image'
import ReciepItem from '@/components/RecipeItem'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Pocket Chef</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
        <h1>Pocket Chef</h1>
        {data.recipes.map(item =>
          <ReciepItem key={item.title} item={item} /> 
        )}
      </main>
    </>
  )
}

export async function getServerSideProps({res}) {
  //s-maxage: secons this value is considered fresh
  //stale-while-revalidate: stale-while-revalidate.
  //The steal value will be rendered but in th background will be a petition for the new value

  res.setHeader(
    'Cache-Control',
    'public, s-maxage=3600, stale-while-revalidate=7200'
  )

  const response = await fetch(`https://api.spoonacular.com/recipes/random?number=10&apiKey=${process.env.SPOONACULAR_API_KEY}`)
  const data = await response.json()


  return { props: { data } }
}
